# Generated by Django 2.1.2 on 2018-10-18 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0004_bid_bid_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='location',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='auction',
            name='status',
            field=models.CharField(default='U', max_length=1),
        ),
    ]
